import { api } from '../api';

export interface TableLayout {
  _id?: string;
  name: string;
  gridCols: number;
  gridRows: number;
  isActive?: boolean;
  zones?: {
    zoneId: string;
    zoneName: string;
    bounds: { x1: number; y1: number; x2: number; y2: number };
  }[];
  tables: {
    tableId: string;
    tableName: string;
    position: { x: number; y: number; rotation?: number };
    width?: number;
    height?: number;
    zoneName?: string;
    type?: string;
    capacity?: number;
  }[];
  backgroundImage?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateLayoutDto {
  name: string;
  gridCols: number;
  gridRows: number;
  isActive?: boolean;
  zones?: TableLayout['zones'];
  tables: TableLayout['tables'];
  backgroundImage?: string;
  description?: string;
}

export interface UpdateLayoutDto {
  name?: string;
  gridCols?: number;
  gridRows?: number;
  isActive?: boolean;
  zones?: TableLayout['zones'];
  tables?: TableLayout['tables'];
  backgroundImage?: string;
  description?: string;
}

/**
 * Get all table layouts
 */
export const getLayouts = async (): Promise<TableLayout[]> => {
  try {
    const response = await api.get('/table-layouts');
    return response.data?.data || response.data || [];
  } catch (error) {
    console.error('Error fetching layouts:', error);
    return [];
  }
};

/**
 * Get active table layout
 */
export const getActiveLayout = async (): Promise<TableLayout | null> => {
  try {
    const response = await api.get('/table-layouts/active');
    return response.data?.data || response.data || null;
  } catch (error) {
    console.error('Error fetching active layout:', error);
    return null;
  }
};

/**
 * Get a single table layout by ID
 */
export const getLayout = async (id: string): Promise<TableLayout> => {
  const response = await api.get(`/table-layouts/${id}`);
  return response.data?.data || response.data;
};

/**
 * Create a new table layout
 */
export const createLayout = async (data: CreateLayoutDto): Promise<TableLayout> => {
  const response = await api.post('/table-layouts', data);
  return response.data?.data || response.data;
};

/**
 * Update a table layout
 */
export const updateLayout = async (
  id: string,
  data: UpdateLayoutDto
): Promise<TableLayout> => {
  const response = await api.patch(`/table-layouts/${id}`, data);
  return response.data?.data || response.data;
};

/**
 * Set a layout as active (and set others as inactive)
 */
export const setActiveLayout = async (id: string): Promise<TableLayout> => {
  const response = await api.patch(`/table-layouts/${id}/set-active`);
  return response.data?.data || response.data;
};

/**
 * Delete a table layout
 */
export const deleteLayout = async (id: string): Promise<void> => {
  await api.delete(`/table-layouts/${id}`);
};

/**
 * Migrate layouts from localStorage to database
 */
export const migrateLayoutsFromLocalStorage = async (): Promise<{
  success: boolean;
  migratedCount: number;
  message: string;
}> => {
  try {
    const saved = localStorage.getItem('table-layouts');
    if (!saved) {
      return {
        success: false,
        migratedCount: 0,
        message: 'No layouts found in localStorage'
      };
    }

    const layouts: TableLayout[] = JSON.parse(saved);
    let migratedCount = 0;

    for (const layout of layouts) {
      try {
        // Remove _id if exists (will be generated by backend)
        const { _id, createdAt, updatedAt, ...layoutData } = layout;
        await createLayout(layoutData);
        migratedCount++;
      } catch (error) {
        console.error(`Error migrating layout "${layout.name}":`, error);
      }
    }

    return {
      success: true,
      migratedCount,
      message: `Successfully migrated ${migratedCount} layout(s)`
    };
  } catch (error) {
    console.error('Error during migration:', error);
    return {
      success: false,
      migratedCount: 0,
      message: 'Migration failed'
    };
  }
};
